# Generated by Django 3.2.23 on 2023-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearlist',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('bike', 'Bike'), ('climbing', 'Climbing'), ('hiking', 'Hiking')], default='other', max_length=20),
        ),
    ]
